/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class sen_com_fmod_EffectUtils */

#ifndef _Included_sen_com_fmod_EffectUtils
#define _Included_sen_com_fmod_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef sen_com_fmod_EffectUtils_TYPE_NORMAL
#define sen_com_fmod_EffectUtils_TYPE_NORMAL 0L
/*
 * Class:     sen_com_fmod_EffectUtils
 * Method:    playNormal
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_sen_com_fmod_EffectUtils_playNormal
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
